### ISSUE TITLE
How to generate the  "Demo"?

### ISSUE THREAD

**Issue by luciusun** [zhegan27/Semantic_Compositional_Nets#2]
hi, @zhegan27 
thank you for your code. when i run "Demo: generating image tags and captions from scratch",
I can reproduct the anwser, but i don't know the theory how to produce the “bin”，please  help me,
thansk

**Comment by zhegan27** [comment]
sorry, I am also not sure how to produce the "bin", as I basically just used this tool which is provided by Microsoft. 

Best,
Zhe

**Comment by luciusun** [comment]
@zhegan27 , could you give me some materials about ‘’bin”？thank you very much

**Comment by zhegan27** [comment]
sorry that I also do not know useful materials about "bin", I am also not good at that, just like you, and I only used that as a tool. Maybe you can find some other experts that are good at it. :)

**Comment by huohuanriri** [comment]
hello, thank  u for the code. Is it possible that I just run the training process on the CPU device?? cause I don't have a GPU device~~

**Comment by zhegan27** [comment]
Yes, I think you can run the theano code directly on the CPU device as long as the theano package is installed.
