### ISSUE TITLE
Hi, I have a question about the training process.

### ISSUE THREAD

**Issue by hyf6661669** [zhegan27/Semantic_Compositional_Nets#3]
Hello, @zhegan27
Much thanks for sharing your code. In the introduction, you mention that "On a modern GPU, the model will take one night to train." 

Can you tell me the specific GPU you used for training, and the specific time for training? Since we can't afford a GPU device, we want to estimate the time required for the entire training process using a CPU device. 

I'm looking forward to your favourable reply. Thanks!

**Comment by zhegan27** [comment]
The specific GPU that I have used for trained during the time of paper writing was a NVIDIA
GeForce GTX TITAN X GPU with 12GB memory. It took roughly 12-13 hours for training. 

Hope it helps your research!
