### ISSUE TITLE
Tags extraction code.

### ISSUE THREAD

**Issue by mememimis** [zhegan27/Semantic_Compositional_Nets#4]
Hi, I'm wondering if it is possible to release the code  for the semantic concept detection.

Thank you,

Mimis

**Comment by zhegan27** [comment]
The code is actually already provided. See the section: Demo: generating image tags and captions from scratch. It contains pre-trained model that do image tagging and image captioning end-to-end. 

If you are asking the training code of the image tagger, I do not have such code at hand. But for pre-trained image tagger, it is already there. 

Hope it helps your research!

**Comment by nicholasmireles** [comment]
So the only way to get tags and features from an image is through the trained model provided in demo.exe?

**Comment by zhegan27** [comment]
yes, that's what I have for extracting tags. But for ResNet feature extraction, there should be a lot other PyTorch or Tensorflow tools that you can search. Hope it helps!
