### ISSUE TITLE
Tensorflow or PyTorch?

### ISSUE THREAD

**Issue by akskuchi** [zhegan27/Semantic_Compositional_Nets#5]
Hello,

Firstly, thanks a lot for making the code public. I would like to port the code to tensorflow/pytorch. Do you think that would be straightforward?

Thanks!

**Comment by zhegan27** [comment]
At the time of starting the project, Theano is still popular, so the code is based on Theano. As the idea in this paper is relatively easy to understand and implement, and I have provided the tags and image features that we used for training, I think it will not be difficult to transfer the code to tensorflow/pytorch, and reproduce the results. The only tricky part is that you may need to define a new LSTM cell that implements SCN-LSTM. However, I still think it should be straightforward.

Besides the tags used in this paper, you can also replace the ResNet features used in this paper by more advanced Bottom-up-attention features. 

Hope it helps!

**Comment by akskuchi** [comment]
Great! Will update you if I can get it working using other frameworks.
Thanks a lot!
